# TinyLlama - Ultra-lightweight model
# 1.1B parameters - Fastest possible, good for simple tasks
name: tinyllama
parameters:
  model: huggingface://TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
context_size: 2048
threads: 4
stopwords:
  - "</s>"
  - "<|user|>"
  - "<|assistant|>"
template:
  chat_message: |
    <|{{.RoleName}}|>
    {{.Content}}</s>
  chat: |
    {{.Input}}
    <|assistant|>
