apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vauban

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ipfs-deployment.yaml
  - redis-deployment.yaml
  - madara-deployment.yaml
  - configmaps.yaml
  - secrets.yaml
  - ingress.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: vauban-blog
  app.kubernetes.io/managed-by: kustomize
