apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vauban-staging

resources:
  - ../../base

# Override namespace
patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: vauban-staging
    target:
      kind: "*"
      namespace: vauban

# Staging images (use latest or specific dev tags)
images:
  - name: ghcr.io/vauban/frontend
    newTag: "latest"
  - name: ghcr.io/vauban/madara
    newTag: "latest"

# Staging ConfigMap
configMapGenerator:
  - name: frontend-config
    behavior: merge
    literals:
      - NEXT_PUBLIC_BASE_URL=https://staging.vauban.blog

# Staging ingress patch
patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.vauban.blog
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.vauban.blog
      - op: remove
        path: /spec/rules/1
      - op: remove
        path: /spec/tls/0/hosts/1
    target:
      kind: Ingress
      name: vauban-ingress

commonLabels:
  environment: staging
